package com.xhgj.bigdata.util

/**
 * @Author luoxin
 * @Date 2023/4/26 11:08
 * @PackageName:com.xhgj.bigdata.util
 * @ClassName: TableName
 * @Description: TODO
 * @Version 1.0
 */
object TableName {
  val ODS = "ODS_XHGJ."
  val ODS_TMP = "ODS_XHGJ_TMP."
  //费用类型的列表表名
  val FEE_TYPR_TABLENAEM = ODS + "YKB_FEE_TYPE"
  val T_AR_RECEIVABLEENTRY = ODS_TMP + "T_AR_RECEIVABLEENTRY"
  val T_AR_RECEIVABLE = ODS_TMP + "T_AR_RECEIVABLE"
  val PXDF_PROJECTBASIC = ODS_TMP + "PXDF_PROJECTBASIC"
  val PXDF_PROJECTBASIC_L = ODS_TMP + "PXDF_PROJECTBASIC_L"
  val T_ORG_ORGANIZATIONS = ODS_TMP + "T_ORG_ORGANIZATIONS"
  val T_BD_CUSTOMER = ODS_TMP + "T_BD_CUSTOMER"
  val T_BD_CUSTOMER_L = ODS_TMP + "T_BD_CUSTOMER_L"
  val T_ORG_ORGANIZATIONS_L = ODS_TMP + "T_ORG_ORGANIZATIONS_L"
  val T_BD_MATERIAL = ODS_TMP + "T_BD_MATERIAL"
  val T_BD_MATERIAL_L = ODS_TMP + "T_BD_MATERIAL_L"
  val T_BD_MATERIALGROUP = ODS_TMP + "T_BD_MATERIALGROUP"
  val PXDF_WRITEOFFADJUST = ODS_TMP + "PXDF_WRITEOFFADJUST"
  val T_AR_SOCCOSTENTRY = ODS_TMP + "T_AR_SOCCOSTENTRY"
  val T_AR_RECEIVABLEENTRY_O = ODS_TMP + "T_AR_RECEIVABLEENTRY_O"
  val PAEZ_T_CUST_ENTRY100020 = ODS_TMP + "PAEZ_T_CUST_ENTRY100020"
  val Paez_t_Cust_Entry100020_l = ODS_TMP + "Paez_t_Cust_Entry100020_l"
  val PAEZ_t_Cust_Entry100002_L = ODS_TMP + "PAEZ_t_Cust_Entry100002_L"


}
